### ISSUE TITLE
双击中文字体会出现重影现象

### ISSUE THREAD

**Issue by hemingyang** [javascript-tutorial/zh.javascript.info#767]
![image](https://user-images.githubusercontent.com/28049728/86248756-e22eae80-bbe0-11ea-99ea-2ea8dbac90ef.png)

**Comment by leviding** [comment]
您好，我这测试没有这种问题呢，是不是浏览器或者显示器不同而造成的呢？

**Comment by hemingyang** [comment]
![image](https://user-images.githubusercontent.com/28049728/86305151-8d704f80-bc43-11ea-98ef-e15b13f2e318.png)
代码演示区的注释,会出现  我用其他电脑也是一样 不严重,只是看着不舒服 估计是代码背景皮肤的原因

**Comment by leviding** [comment]
<img width="834" alt="Screen Shot 2020-07-02 at 4 57 30 PM" src="https://user-images.githubusercontent.com/26959437/86338652-28d5e480-bc85-11ea-955c-fd86682d019d.png">

这是我这边的显示效果，感谢指出。

**Comment by leviding** [comment]
我们再检查一下吧，感谢指出 👍

**Comment by summer1874** [comment]
```css
color black, pre[class*=language-], pre[class*=language-]>code {
  text-shadow: 0 1px #fff; // 引发选中重影
  font-family: Consolas,Lucida Console,Menlo,Monaco,monospace;
  direction: ltr;
  text-align: left;
  white-space: pre;
  word-spacing: normal;
  -moz-tab-size: 4;
  tab-size: 4;
  -webkit-hyphens: none;
  -ms-hyphens: none;
  hyphens: none;
}
```
![font](https://pic.downk.cc/item/5f69c902160a154a673f98a1.png)
