### ISSUE TITLE
教程网站 - 评论 - 阅读内容那里的「提交一个 GitHub issue」对应的链接地址错误

### ISSUE THREAD

**Issue by wordpure** [javascript-tutorial/zh.javascript.info#854]
教程评论那里的「提交一个 GitHub issue」，跳转的链接似乎都是当前页面，而不是 GitHub 仓库的 Issues 链接地址。

![image](https://user-images.githubusercontent.com/68013962/99753988-6cd96100-2b22-11eb-9d42-599acd3b93a9.png)
![image](https://user-images.githubusercontent.com/68013962/99754239-f38e3e00-2b22-11eb-8583-14bc28bd8f54.png)
![image](https://user-images.githubusercontent.com/68013962/99754242-f426d480-2b22-11eb-823c-8e751d323a98.png)

**Comment by leviding** [comment]
@iliakan The link before comments is wrong, needs to be fixed.

**Comment by leviding** [comment]
Besides, on the about page https://zh.javascript.info/about, some information needs an update:


1. In the picture below:
    a. Change "团队" to "团队成员", where with number 1.
    b. Change "管理员" to "管理员，JS — 开发者".

![image](https://user-images.githubusercontent.com/26959437/99768283-79b87d80-2b3f-11eb-92a4-6dc974b47e23.png)

2. Translate some updates into Chinese which is shown in the picture below:

The translation is:

```
教程维护者

本教程的 GitHub 仓库请见 https://github.com/javascript-tutorial/zh.javascript.info。
```

![image](https://user-images.githubusercontent.com/26959437/99768694-33175300-2b40-11eb-946d-4fcac0a2a360.png)

**Comment by leviding** [comment]
@iliakan This issue needs to be fixed.

**Comment by iliakan** [comment]
@leviding here's `zh.yml` (and `en.yml` for comparison), please fix what's appropriate?
Let me know if I need to fix templates also.

[Archive.zip](https://github.com/javascript-tutorial/zh.javascript.info/files/5595129/Archive.zip)

**Comment by leviding** [comment]
@iliakan OK

**Comment by leviding** [comment]
@iliakan DONE.

1. Link before the comment part is wrong and needs to be changed to https://github.com/javascript-tutorial/zh.javascript.info/issues.

![](https://user-images.githubusercontent.com/68013962/99753988-6cd96100-2b22-11eb-9d42-599acd3b93a9.png)

2. Update zh.yml:

```yml
maintainers: 教程维护者
repo: 本教程的 GitHub 仓库请见 <a href="#{url}">#{url}</a>。

team:
  block_title: 团队成员
  photo: 照片

  members:
    - name: "Levi Ding"
      role: admin_developer

  role:
    admin_developer: 管理员，JS — 开发者
    developer_teacher: JS — 开发者，教师

contributors:
  description: >
    <p>下面的列表包括了所有为本教程贡献 10+ 行内容的贡献者。完整的贡献者列表可 <a href="#{url}/graphs/contributors">点击此处</a> 获取。本教程基于 <a href="https://javascript.info">英文版</a> 翻译而来。</p>
    <p>想要让自己也被展示在这里，其实非常简单。只需要写一篇能够被收录到本教程的文章，在 GitHub 上修复 <a href="#{url}">本教程</a> 出现的问题，或者参与本教程的翻译。你会收到来自每一位读者和贡献者的感谢。</p>

```
